{% set name = "grpc-cpp" %}
{% set version = "1.28.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  - url: https://github.com/grpc/grpc/archive/v{{ version }}.tar.gz
    sha256: 4cbce7f708917b6e58b631c24c59fe720acc8fef5f959df9a58cdf9558d0a79b

build:
  number: 2
  # Requires C++ 11, VS 2008 is not supported
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('grpc-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    # `protoc` is also used for building
    - libprotobuf
    - ninja
  host:
    - abseil-cpp
    - c-ares
    - gflags
    - libprotobuf
    - openssl
    - zlib
  run:
    - abseil-cpp
    - zlib

about:
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
  description: |
    gRPC is a modern, open source, high-performance remote procedure call
    (RPC) framework that can run anywhere. gRPC enables client and server
    applications to communicate transparently, and simplifies the building
    of connected systems.

    This package contains the gRPC C++ libraries and header files, as well
    as the code generation plugins.
  doc_url: https://grpc.io/docs/

extra:
  recipe-maintainers:
    - pitrou
    - xhochy
    - wesm
